### ISSUE TITLE
valueContains是不是有bug？

### ISSUE THREAD

**Issue by ssfanli** [openatx/facebook-wda#102]
今天看源码无意间发现，这块的，`value CONTAINS`在接收`_value_part`时候是不是单引号用错了（没调试，暂无证实）
![image](https://user-images.githubusercontent.com/53210634/109251706-e621d780-7826-11eb-86b2-0bef6df3db9b.png)

**Comment by chongchong** [comment]
是的 调试下来有问题 @codeskyblue

**Comment by codeskyblue** [comment]
哈哈，马上改

**Comment by codeskyblue** [comment]
fixed in 1.4.1
