### ISSUE TITLE
facebook/WebDriverAgent废弃了一批endpoint定义，这个工程需要对应的修改

### ISSUE THREAD

**Issue by riccoyu** [openatx/facebook-wda#13]
春节前WebDriverAgent参照WD spec调整了接口url地址。直到最近，旧的接口url地址被废弃了 https://github.com/facebook/WebDriverAgent/commit/dccf5c8fda793b9eaa26a41c4d5637cd42010730
此工程需要对应的修改

| before | after | status |
| --- | --- | --- |
| POST /homescreen | POST /wda/homescreen | done |
| POST /deactivateApp | POST /wda/deactivateApp | done |
| POST /source | GET /source | done|
| GET /window/:uuid/size | GET /window/size | done |
| POST /element/:uuid/pinch | POST /wda/element/:uuid/pinch | not tested |
| GET /element/:uuid/accessible | GET /wda/element/:uuid/accessible | done |
| GET /element/:uuid/accessibilityContainer | GET /wda/element/:uuid/accessibilityContainer |
| POST /uiaElement/:uuid/doubleTap | POST /wda/element/:uuid/doubleTap | done |
| POST /uiaElement/:uuid/twoFingerTap | POST /wda/element/:uuid/twoFingerTap |
| POST /uiaElement/:uuid/touchAndHold | POST /wda/element/:uuid/touchAndHold | done |
| POST /uiaElement/:uuid/scroll | POST /wda/element/:uuid/scroll |
| POST /uiaTarget/:uuid/dragfromtoforduration | POST /wda/element/:uuid/dragfromtoforduration | not implemented |
| POST /tap/:uuid | POST /wda/tap/:uuid | done |
| POST /touchAndHold | POST /wda/touchAndHold | done |
| POST /doubleTap | POST /wda/doubleTap | done |
| POST /keys | POST /wda/keys | done |
| GET /uiaElement/:uuid/getVisibleCells | GET /wda/element/:uuid/getVisibleCells |
| GET /healthcheck | GET /wda/healthcheck | done |
| POST /simulator/touch_id | POST /wda/touch_id |

**Comment by codeskyblue** [comment]
<https://github.com/openatx/facebook-wda/pull/12/files> 还没测试，@riccoyu 要是条件可以，可以帮测试下

**Comment by codeskyblue** [comment]
其他的接口似乎暂时不太需要，需要的时候再reopen下issue
