### ISSUE TITLE
Delay on tap and swipe action 

### ISSUE THREAD

**Issue by tademmahesh** [openatx/facebook-wda#130]
Getting some delay on tap and swipe actions
I don't find any solutions in Readme, Please help!

**Comment by codeskyblue** [comment]
wraps into another function, eg

```python
def delay_tap(x, y):
    time.sleep(1.0)
    d.tap(x, y)
```

**Comment by tademmahesh** [comment]
@codeskyblue  It is delaying the actions I don't want to delay it.
