### ISSUE TITLE
Keep checking status of http+usbmux

### ISSUE THREAD

**Issue by jagdish-mozark** [openatx/facebook-wda#134]
I made sample program to make connection of webdriver agent with usbclient, 

Sample program

```
import wda

wda.DEBUG = True
wda.HTTP_TIMEOUT = 60.0

c = wda.USBClient("00008110-001E2C401443401E", port=8100)

print(c.status)

```

Here is the output of program, It keeps checking status..

Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
[I 230523 06:24:45 __init__:245] WDA is not running, exec: /usr/local/bin/tidevice xctest
[I 230523 06:24:45 _device:984] BundleID: com.facebook.WebDriverAgentRunner.xctrunner
[I 230523 06:24:45 _device:1000] ProductVersion: 16.1.2
[I 230523 06:24:45 _device:1001] DeviceIdentifier: 00008110-001E2C401443401E
[I 230523 06:24:45 _device:837] SignIdentity: 'Apple Development: Jay Panchal (V6325QBF5A)'
[I 230523 06:24:45 _device:843] CFBundleExecutable: WebDriverAgentRunner-Runner
[I 230523 06:24:45 _device:874] AppContainer: /private/var/mobile/Containers/Data/Application/8483E6D9-87F4-4BAC-85D4-C670D1CBB5A7
[I 230523 06:24:45 _device:1122] xctrunner quited
[W 230523 06:24:45 _device:941] WebDriverAgentRunner quitted
[I 230523 06:24:45 _device:914] Launch 'com.facebook.WebDriverAgentRunner.xctrunner' pid: 773
[I 230523 06:24:45 _device:1050] Test runner ready detected
[I 230523 06:24:45 _device:1042] Start execute test plan with IDE version: 29
[I 230523 06:24:46 _device:950] WebDriverAgent start successfully
facebook-wda Tue May 23 06:24:48 2023 Wait ready (timeout=20.0)
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:48 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 20.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:49 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 19.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:50 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 18.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:51 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 17.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:52 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 16.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:53 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 15.0 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:54 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 13.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:55 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 12.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:56 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 11.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:57 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 10.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:58 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 9.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:24:59 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 8.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:00 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 7.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:01 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 6.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:02 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 5.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:03 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 4.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:04 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 3.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:05 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 2.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:06 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 1.9 seconds
Shell$ curl -X GET -d '' 'http+usbmux://00008110-001E2C401443401E:8100/status'
facebook-wda Tue May 23 06:25:07 2023 'http+usbmux://00008110-001E2C401443401E:8100' wait_ready left 0.9 seconds
facebook-wda Tue May 23 06:25:08 2023 device still offline
Traceback (most recent call last):
  File "/aws-samples/app-testing-controller-stack/controller_interact/demo_wda.py", line 6, in <module>
    c = wda.USBClient("00008110-001E2C401443401E", port=8100)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wda/__init__.py", line 1813, in __init__
    raise RuntimeError("wda xctest launched but check failed")
RuntimeError: wda xctest launched but check failed

**Comment by Ryaningli** [comment]
the same issue

**Comment by 552468054** [comment]
同样的问题，有大佬解决了吗？麻烦给点提示

**Comment by Giteers** [comment]
是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1

**Comment by AHuaner** [comment]
卡到这一步了，有没有大佬给个提示

**Comment by ghb0224** [comment]
> 是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1

请问是windows下使用的吗，我也是17.4.1，tidevice3与手机上wda连不上啊

**Comment by Ryaningli** [comment]
> > 是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1
> 
> 请问是windows下使用的吗，我也是17.4.1，tidevice3与手机上wda连不上啊

有打开iTunes么？

**Comment by ghb0224** [comment]
> > > 是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1
> > 
> > 
> > 请问是windows下使用的吗，我也是17.4.1，tidevice3与手机上wda连不上啊
> 
> 有打开iTunes么？

在t3 tunnel时就报错了

C:\Mindows\system32>t3 tunneld
Started server process [14792]
Waiting for application startup.
2024-04-24 16:05:16 DZ-DN-20220137 tidevice3.cli.tumne1d[14792] INFO [00008110-001824AE22BA201E]cmd:
Application startup complete.
Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to qui
Exception in thread 00008110-001824AE22BA201E keeper:
「raceback (most recent call last):
File "D:\python\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "D:\python\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "D:\python\lib\site-packages\tidevice3\cli\tunneld.py", line 116, in _start_tunnel_keeper
addr, process = start_tunnel (self.pmd3_path, udid)
File "D:\python\lib\site-packages\tidevice3\utils\common.py", line 28,in wrapper
return fn(*args, **kwargs)
File "D:\python\'lib\site-packages\tidevice3\cli\tunneld.py", line 69, irstart_tunnel
process = subprocess.Popen(
File "D:\python\lib\subprocess.py", line 971, in _init_
File "D:\python\lib\subprocess.py", line 1456, in _execute_child
self._execute_child(args, executable, preexec_fn, close_fds,
7ileNotFoundError:[WinError2]系统找不倒指定的文件。
hp, ht, pid, tid = winapi.CreateProcess(executable, args,

**Comment by ghb0224** [comment]
> > > 是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1
> > 
> > 
> > 请问是windows下使用的吗，我也是17.4.1，tidevice3与手机上wda连不上啊
> 
> 有打开iTunes么？

t3 tunnel这一步可以省略掉吗，可以直接与wda链接吗

**Comment by jinjf553** [comment]
在win11上我也遇到了同样的问题，我在win10上测试就是正常的。不知道是不是跟windows系统有关系。

**Comment by jinjf553** [comment]
> 在win11上我也遇到了同样的问题，我在win10上测试就是正常的。不知道是不是跟windows系统有关系。

没想到在win10跑通一次后，再回到win11测试时就没有上面的问题了。真奇怪啊

**Comment by codeskyblue** [comment]
> > > > 是wda服务访问/status时没有返回导致，但是我的设备上看起来wda服务是拉起来了，但是也没法访问/status。我的环境是iOS17.4.1
> 
> > > 
> 
> > > 
> 
> > > 请问是windows下使用的吗，我也是17.4.1，tidevice3与手机上wda连不上啊
> 
> > 
> 
> > 有打开iTunes么？
> 
> 
> 
> 在t3 tunnel时就报错了
> 
> 
> 
> C:\Mindows\system32>t3 tunneld
> 
> Started server process [14792]
> 
> Waiting for application startup.
> 
> 2024-04-24 16:05:16 DZ-DN-20220137 tidevice3.cli.tumne1d[14792] INFO [00008110-001824AE22BA201E]cmd:
> 
> Application startup complete.
> 
> Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to qui
> 
> Exception in thread 00008110-001824AE22BA201E keeper:
> 
> 「raceback (most recent call last):
> 
> File "D:\python\lib\threading.py", line 1016, in _bootstrap_inner
> 
> self.run()
> 
> File "D:\python\lib\threading.py", line 953, in run
> 
> self._target(*self._args, **self._kwargs)
> 
> File "D:\python\lib\site-packages\tidevice3\cli\tunneld.py", line 116, in _start_tunnel_keeper
> 
> addr, process = start_tunnel (self.pmd3_path, udid)
> 
> File "D:\python\lib\site-packages\tidevice3\utils\common.py", line 28,in wrapper
> 
> return fn(*args, **kwargs)
> 
> File "D:\python\'lib\site-packages\tidevice3\cli\tunneld.py", line 69, irstart_tunnel
> 
> process = subprocess.Popen(
> 
> File "D:\python\lib\subprocess.py", line 971, in _init_
> 
> File "D:\python\lib\subprocess.py", line 1456, in _execute_child
> 
> self._execute_child(args, executable, preexec_fn, close_fds,
> 
> 7ileNotFoundError:[WinError2]系统找不倒指定的文件。
> 
> hp, ht, pid, tid = winapi.CreateProcess(executable, args,
> 
> 

这个问题还有吗？最新版

**Comment by Wing-YQ-Chen** [comment]
> python环境切到3.6再试试，我试的3.6之后的都会报上面的错误
![image](https://github.com/openatx/facebook-wda/assets/121747854/531c16d4-4087-4ceb-9bcd-889b03cf14e0)

我也是，Win11 + iOS15.5 + facebook-wda 1.4.7
pythom3.11 会报这个错
python 3.6   没有报错

**Comment by Wing-YQ-Chen** [comment]
> python环境切到3.6再试试，我试的3.6之后的都会报上面的错误

我也是，Win11 + iOS15.5 + facebook-wda 1.4.7
pythom3.11 会报这个错
python 3.6   没有报错

**Comment by lycfr** [comment]
Mac OS：13.6.5
iOS：14.7
facebook-wda：1.4.7
python：3.10.9
同样遇到这个问题，你们有解吗？

**Comment by lycfr** [comment]
@AHuaner 按照你的方解决了，大佬6666

**Comment by Wing-YQ-Chen** [comment]
> 依赖的requests 需要2.28.2以下，应该就不会报错了

@AHuaner  Big thanks bro!!!

@codeskyblue 建議置頂一下

**Comment by iAtlantis** [comment]
真的建议置顶，这个问题查到真的很折磨。

**Comment by codeskyblue** [comment]
fixed。不过需要python3.8以上。
