### ISSUE TITLE
目前e.set_text()与e.clear_text()都无效了

### ISSUE THREAD

**Issue by hanyibo520** [openatx/facebook-wda#141]
目前WebDriverAgent6.0.0版本，e.set_text()与e.clear_text()都无效了

**Comment by youngfreeFJS** [comment]
https://github.com/openatx/facebook-wda/blob/master/e2e_benchmarks/reports/WDA_V611.md
6.1.1版本测试报告无问题，建议升级版本或提交详细错误代码、日志
