### ISSUE TITLE
tap命令在最新版本wda上存在不兼容的升级，详见desc

### ISSUE THREAD

**Issue by youngfreeFJS** [openatx/facebook-wda#142]
### ⚠ BREAKING CHANGES

* The  /wda/tap/:uuid endpoint has been replaced by /wda/element/:uuid/tap and /wda/tap ones

https://github.com/appium/WebDriverAgent/blob/8c868dca02269cd40ef50c0746f265bcf603baa0/CHANGELOG.md?plain=1#L100

**Comment by codeskyblue** [comment]
看来需要升一下大版本号了

**Comment by youngfreeFJS** [comment]
#144 Fixed
