### ISSUE TITLE
Warning: prefer use className instead of class_name

### ISSUE THREAD

**Issue by DoubleHYH** [openatx/facebook-wda#28]
class Session 的 `__call__` 方法中会将 className 参数改为 class_name。class Selector `__init__` 方法中当 class_name 参数不为空时会输出

    Warning: prefer use className instead of class_name
结果就是只要用到 className 的时候不管用 `className` 还是 `class_name` 都会打印这条 Warning

**Comment by codeskyblue** [comment]
`class_name` 已经去除，警告也删掉了
