### ISSUE TITLE
Element 类没有 alert_callback

### ISSUE THREAD

**Issue by DoubleHYH** [openatx/facebook-wda#30]
RT

**Comment by codeskyblue** [comment]
可能放到Selector里面更好

**Comment by DoubleHYH** [comment]
不一定，毕竟 click 这个动作是跑到 Selector 里了

**Comment by codeskyblue** [comment]
也许放在Session里面，比Selector，Element里面更好。毕竟弹窗是App的一个东东，你不知道他什么时候会突然蹦出来

**Comment by DoubleHYH** [comment]
要我说还不如放在 `httpdo` 方法里。这个位置才能保证对所有的弹窗都捕捉到。而且放在这里还可以对host进行比对来判断设备，顺手就把多设备的问题也搞定了

**Comment by codeskyblue** [comment]
因为需要session才能访问alert，所以现在转移到了 Session中，用法如下

```python
def callback(session):
    session.alert.accept()

s.set_alert_callback(callback)
```
