### ISSUE TITLE
how did I know the index of founded elements，it could be -2 or -1？

### ISSUE THREAD

**Issue by NeowuqiLee** [openatx/facebook-wda#40]
what is the beginning index of the founded elements array ？
![image](https://user-images.githubusercontent.com/12151989/34511235-f97b2cea-f094-11e7-911b-6d5fb0263dcc.png)

**Comment by codeskyblue** [comment]
what do you want it like?

**Comment by NeowuqiLee** [comment]
As I know, the API findElementByAndroidUIAutomator  in Appium will return the index of founded elements with  beginning  0 to n, that is nice

**Comment by codeskyblue** [comment]
need more details.

**Comment by NeowuqiLee** [comment]
solved  by hardcode the element index
