### ISSUE TITLE
tap method has a bug

### ISSUE THREAD

**Issue by zhoilet** [openatx/facebook-wda#44]
Hi,

I found that when I use wda_session.tap(x, y) method on my iPad, there is a 50% difference. 

For example, if I want to tap (100, 200) on my iPad screen, I have to use wda_session.tap(50, 100).

I have to add a new function to my code like this:

```
def click(wda_session, x, y):
	'''
	wda has a bug
	'''
	wda_session.tap(x//2, y//2)
```

**Comment by zhoilet** [comment]
Is there any reason for this **feature**?

**Comment by codeskyblue** [comment]
I donot know. iOS device always has a scale. some is 2x(Like your ipad), some device is 3x

**Comment by codeskyblue** [comment]
Refs: https://github.com/openatx/facebook-wda/issues/52
