### ISSUE TITLE
iOS11通过bundleID不能代开应用

### ISSUE THREAD

**Issue by CoderFeiSu** [openatx/facebook-wda#45]
iOS9可以通过bundle打开应用、iOS11不行、请问是什么原因

**Comment by codeskyblue** [comment]
不知道，你提供的线索太少了

**Comment by CoderFeiSu** [comment]
你需要哪些线索 我都提供给你

**Comment by codeskyblue** [comment]
跟wda交互的内容，具体复线方法

**Comment by CoderFeiSu** [comment]
开发环境Xcode9.2   Python3   MacOS10.12.6
比方说在iOS9里面执行以下代码会打开 健康 这个软件  iOS11打不开
c = wda.Client('http://192.168.1.15:8100') # DEVICE_URL
c.session('com.apple.Health')

**Comment by codeskyblue** [comment]
我还是不太能看出来，升级下WDA，和facebook-wda试试，还是不行，暂时我也没办法了
