### ISSUE TITLE
how to make swipe faster and continuous？

### ISSUE THREAD

**Issue by smaugx** [openatx/facebook-wda#49]
I want to do continuous swipe  as faster as it can do, but how?
 
I don't find any solutions in Readme,Please help!

**Comment by codeskyblue** [comment]
https://github.com/openatx/facebook-wda/blob/master/wda/__init__.py#L399
set duration to smaller

**Comment by smaugx** [comment]
@codeskyblue  not work very well, even though duration is very small, like  0.000000001.  

swipe still slow and not continuous.

**Comment by codeskyblue** [comment]
You may create issue in github.com/facebook/WebDriverAgent, there is nothing more we can do.

**Comment by smaugx** [comment]
Ok。Thanks!

shengxiang <notifications@github.com>于2018年6月25日 周一下午7:15写道：
