### ISSUE TITLE
swipe速度好慢，调了第5个参数也还是没用

### ISSUE THREAD

**Issue by zacard-orc** [openatx/facebook-wda#51]
swipe速度好慢，调了第5个参数也还是没用，有源码哪里可以改的粗暴一点啊

**Comment by CeaserW** [comment]
找到方法了吗

**Comment by CeaserW** [comment]
> swipe速度好慢，调了第5个参数也还是没用，有源码哪里可以改的粗暴一点啊

找到方法了吗

**Comment by kennethzhu** [comment]
同求  行业难题啊。。。

**Comment by wsndy163** [comment]
https://github.com/wsndy163/facebook-wda/tree/SwipeKartun
4个文件放到目标工程下，可修正指定工程的swipe的卡顿。

**Comment by zxyhere** [comment]
> https://github.com/wsndy163/facebook-wda/tree/SwipeKartun
> 4个文件放到目标工程下，可修正指定工程的swipe的卡顿。

请问具体是放在哪个目录下？目标工程指的是什么？代码copy进去后，哪个地方需适配什么吗

**Comment by warm200** [comment]
@zxyhere  是 build phase 的compile source里面吧。 但是我没成功 cc: @wsndy163

**Comment by codeskyblue** [comment]
我猜速度慢的主要原因是 wda在滑动前 有一个 等待界面静止的 函数

**Comment by warm200** [comment]
@codeskyblue 也不知道在busy什么要等待idle  像是抖音上滑 
debugger里面全是
 ```Wait for com.ss.iphone.ugc.Aweme to idle
Find the Application 'com.ss.iphone.ugc.Aweme'
    t =   167.15s         Snapshot accessibility hierarchy for app with pid 3085
``` 
不太了解这些都是什么意思 或者有没有什么方式避免， @wsndy163 的方法可能对他有用但是我没弄明白怎么搞

**Comment by yulinho** [comment]
> @codeskyblue 也不知道在busy什么要等待idle 像是抖音上滑
> debugger里面全是
> 
> ```
> Wait for com.ss.iphone.ugc.Aweme to idle
> Find the Application 'com.ss.iphone.ugc.Aweme'
>    t =   167.15s    Snapshot accessibility hierarchy for app with pid 3085
> ```
> 不太了解这些都是什么意思 或者有没有什么方式避免， @wsndy163 的方法可能对他有用但是我没弄明白怎么搞

同求这问题。那么快的a12查找元素这么慢的吗？

**Comment by codeskyblue** [comment]
There is nothing can do here.
