### ISSUE TITLE
session.window_size() return size different with client.screenshot

### ISSUE THREAD

**Issue by sherry0429** [openatx/facebook-wda#52]
First very thanks this great work, i use this to control my ios device. now i must make a function like :

1. screenshot
2.compare a template img ( like button in current screenshot png) with screenshot png
3.output template img's width & height in screenshot

my question is:

1.session.width & height is 1024 * 768
2.screenshot.width & height is 2048 * 1536
these two size is different so when i get template size, it not right at screen.( i guess session.tap is work with session.size. right?)

can you tell me how to make screenshot png with session.size or how to make tap method work with screenshot png axis ? 

thanks!

**Comment by codeskyblue** [comment]
Yes. you found it. UIKit size is different with screen size.
Details can be found in <https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html>
![image](https://user-images.githubusercontent.com/3281689/48176523-5735dc00-e34b-11e8-92f7-cdb4e4fee17b.png)

**Comment by codeskyblue** [comment]
Also you can found more information here. https://www.paintcodeapp.com/news/iphone-6-screens-demystified

**Comment by sherry0429** [comment]
ok, i have get it, 
thanks !

**Comment by abbothzhang** [comment]
how long does it to screenshot
