### ISSUE TITLE
home()方法报错

### ISSUE THREAD

**Issue by wishchen** [openatx/facebook-wda#54]
error:
```
GenericDict(value='Error Domain=com.facebook.WebDriverAgent Code=1 "Timeout waiting until SpringBoard is visible" UserInfo={NSLocalizedDescription=Timeout waiting until SpringBoard is visible}', sessionId='2337B533-0195-492A-BF51-411C70F69B91', status=13)
```

**Comment by codeskyblue** [comment]
确认你没有锁屏吧

**Comment by wishchen** [comment]
@codeskyblue 没有锁屏的

**Comment by wishchen** [comment]
@codeskyblue 
iPhone6s iOS11.4 
Xcode Version 9.4.1 (9F2000)  
macOS High Sierra 10.13.3 (17D47)

**Comment by kennethzhu** [comment]
这个是wda的问题，判断桌面是否出现导致了超时，疑问系统是Docker，中文系统是程序坞。https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/FBSpringboardApplication.m  文件   return self.otherElements[@"Dock"].isEnabled; 改成  return self.otherElements[@"程序坞"].isEnabled; 就好了。

**Comment by wishchen** [comment]
@kennethzhu  研究的比较深，感谢。
更改wda的FBSpringboardApplication.m文件最后的返回为 
`return self.otherElements[@"Dock"].isEnabled || self.otherElements[@"程序坞"].isEnabled;` 问题解决。
@codeskyblue

**Comment by codeskyblue** [comment]
感觉你可以给wda提pr了

**Comment by wishchen** [comment]
@codeskyblue 👍  @kennethzhu 快去提

**Comment by codeskyblue** [comment]
well, The https://github.com/facebook/WebDriverAgent seems archived.

**Comment by codeskyblue** [comment]
最新版本 的 https://github.com/appium/WebDriverAgent 貌似没有这个问题了，issue先关掉了
