### ISSUE TITLE
Desired capability not provided

### ISSUE THREAD

**Issue by Jeffwhen** [openatx/facebook-wda#61]
https://github.com/openatx/facebook-wda/blob/2412383731b9cb28c4b8b69f09f11579700b01af/wda/__init__.py#L299-L303

看了下代码后面 `httpdo` 应该是传给了 `request` 这样的话应该不需要 `json.dumps` 吧。

本地环境把这个 `dumps` 删掉之后可以创建  session 了，否则一只报错连接不上。

**Comment by codeskyblue** [comment]
Thanks, already fixed in 0.2.4, duplicated https://github.com/openatx/facebook-wda/issues/64
