### ISSUE TITLE
iOS 设备并行跑用例

### ISSUE THREAD

**Issue by xinzhen2015** [openatx/facebook-wda#72]
c = wda.Client(‘http://localhost:8100'）

这个地方，设置了不同的端口（8103、8106），log里面看到
WebDriverAgentRunner-Runner[30959:8510846] ServerURLHere->http://169.254.33.58:8100<-ServerURLHere

请问这个地方的8100，是写死的么 😿

**Comment by Roise0568** [comment]
同问，怎么并行测试？

**Comment by Roise0568** [comment]
按照 redme 可以在指定的port上测试一个手机，如果测两个手机（指定不同的port），只有第一个可以成功。请问哪个地方弄错了么？
对A手机操作：
1. 打开WebDriverAgentRunner
2. iproxy 8100 8100
3. c = wda.Client('http://localhost:8100'）
对 B 手机操作：
1. 打开WebDriverAgentRunner
2. iproxy 8100 8101
3. c = wda.Client('http://localhost:8101'）

**Comment by codeskyblue** [comment]
左边是本地端口，右边的数字8100是固定的

**Comment by Roise0568** [comment]
这里应该是WebDriverAgentRunner里面写死的。
按照 facebook-wda readme 的说明，可以实现并行测试：
1. 分别打开、运行 WebDriverAgentRunner（指定对应的设备，version）
2. iproxy 8100 8100 
3. iproxy 8101 8101
4. c1 = wda.Client('http://localhost:8100'）
5. c2 = wda.Client('http://localhost:8100'）

**Comment by codeskyblue** [comment]
给你修正下

1. iproxy -u 第一个设备的udid 8100 8100 
1. iproxy -u 第二个设备的udid 8200 8100 
3. c1 = wda.Client("http://localhost:8100")
3. c2 = wda.Client("http://localhost:8200")
