### ISSUE TITLE
wda 有一些报错，不便于上层识别是哪种类型的错误

### ISSUE THREAD

**Issue by Roise0568** [openatx/facebook-wda#80]
创建session时，有时会出错 KeyError: 'capabilites'，可否提供wda的错误类型，便于捕捉识别错误并处理，谢谢！

class Session(object):
    def __init__(self, httpclient, session_id):
        self.http = httpclient
        self._target = None
        self._timeout = 30.0  # default elment search timeout, change through implicitly_wait(.)
        v = self.http.get('/').value
        try:
            self.capabilities = v['capabilities']
        except KeyError:
            raise AnyWdaErrorType("error message description")

        self._sid = v['sessionId']
        self.__scale = None

**Comment by codeskyblue** [comment]
什么时候会出现？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
