### ISSUE TITLE
What's different between idb and wda?

### ISSUE THREAD

**Issue by hwangjr** [openatx/facebook-wda#95]
https://github.com/facebook/idb 
idb is a flexible command line interface for automating iOS simulators and devices

wda project has been archived, so will you use idb?

**Comment by 541347048** [comment]
哈哈哈




| |
xsxooxsx
|
|
邮箱：xsxooxsx@126.com
|

Signature is customized by Netease Mail Master

On 07/18/2020 15:29, Carlos Hwang wrote:

https://github.com/facebook/idb

**Comment by codeskyblue** [comment]
idb is a flexible command line interface for automating iOS simulators and devices

wda is A WebDriver server for iOS that runs inside the Simulator.

**Comment by codeskyblue** [comment]
idb is a nice tools, it just not working on my mac.
