### ISSUE TITLE
使用text输入文本后，后续其他操作都无法进行了

### ISSUE THREAD

**Issue by test20200324** [openatx/facebook-wda#96]
ios.py的text函数备注bug in wda for now，输入完要怎么才可以继续系一部

**Comment by codeskyblue** [comment]
你把代码也写一下

**Comment by test20200324** [comment]
text（‘123’）
touch（pos）
横屏情况下，在执行输入123，后续的touch就不行了，不过这个我已经解决了，但是是为什么我没有找到原因，使用Airtest的text就是会导致后续操作中断，最后我是用了你的facebook-wda才解决的
所以，我似乎issues提错地方了。。。

**Comment by codeskyblue** [comment]
那issue我先关掉了
